name: vhs
on:
  push:
    branches:
      - master
    paths:
      - '*.tape'
    workflow_dispatch:
jobs:
  vhs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v3
        with:
          go-version-file: go.mod
      - uses: charmbracelet/vhs-action@ci-colors
        with:
          path: 'demo.tape'
        env:
          TERM: xterm-256color
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore: update generated VHS GIF'
          branch: master
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: '*.gif'
